version: '3.8'
services:
  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'

  mongo:
    image: mongo:5
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: musaidbot-api
    ports:
      - '3000:3000'
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/musaid
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=أسرار_هنا
      - WHATSAPP_API_KEY=سر_البوت
      - WHATSAPP_TOKEN=<ويبهوك_توكن>
      - WHATSAPP_PHONE_ID=<رقم_الهاتف_في_Meta>
      - FRONTEND_ORIGIN=http://localhost:4200
      # … متغيّرات بيئية إضافية حسب حاجتك

volumes:
  mongo_data:
