version: '3.8'
services:
  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: musaidbot-backend
    command: npm run start:prod
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  n8n:
    image: n8nio/n8n
    container_name: musaidbot-n8n
    ports:
      - '5678:5678'
    environment:
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://mongo:27017/n8n
      - GENERIC_TIMEZONE=UTC
    depends_on:
      - mongo

volumes:
  mongo_data:
